#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
sudo apt-get install -y jenkins

# Configure Nginx and reload
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$path.conf


data_path=/home/yunohost.app/jenkins

# Copy files to the right place

sudo mkdir -p $data_path
sudo chown -hR jenkins:jenkins $data_path
sudo chmod 775 $data_path


sudo service jenkins stop

sudo cp ../conf/jenkins.default /etc/default/jenkins

sudo service jenkins start

sudo yunohost service add jenkins --log /var/log/jenkins/jenkins.log


sudo service nginx reload
sudo yunohost app ssowatconf