#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

wget -q -O - http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian binary/ > /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
sudo apt-get install -y jenkins



sudo yunohost service add jenkins --log /var/log/jenkins/jenkins.log


